project:
  type: website

website:
  title: "R Programming Journal - Robert Walsh"
  navbar:
    logo: ""
    background: "#006747"
    right:
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: tango

editor: visual

execute:
  freeze: auto
